### ISSUE TITLE
Configure eslint to warn when const could be used over let

### ISSUE THREAD

**Issue by nulltoken** [axa-group/arm-template-merge#7]
#6 review seems to catch a pattern (use `const` over `let`)

Great news! There's an [eslint rule]( https://eslint.org/docs/rules/prefer-const ) for this.

**Proposal:**

 - Let robots waste time so human beings can focus their review on other things
 - Fail the build over that finding

**Comment by poveden** [comment]
You know, I'm aware of that ESLint rule, and I deliberately chose to not use it, because of my _"`const` will never, ever, change"_ mind association. Take this:

```js
function blah(someArg) {
  const times2 = 2;
  const o = {};
  o.field = someArg * times2;
  return o;
}
```
I _know_ that `o` will have a value assigned to it only once, but the human being in me reads _"here is this `o` thing, which will never change, even across invocations of `bla()`."_

The fact that, in JavaScript, `const` really means _"I'm creating a new variable on the stack and assigning to it the value `2`"_, every time `blah()` runs, only makes the semantics of `const` more confusing. This is why I use `const` for things that are meant to be unchanging, and `let` for things that I assign new values, even if I do it only once.

Then comes @jesus-seijas-sp and brings to my attention that "`const` improves performance through optimization of Turbofan for Node 8, liftoff for Node 10", so I'm really willing to consider my stance, but I'd still favor readability over performance if the performance gains are negligible.

Thoughts?

**Comment by jesus-seijas-sp** [comment]
The performance optimization is usually negligible, most of the cases will not exists, but there are optimization rules in both Turbofan and Liftoff. For liftoff, you can find some info here: https://v8.dev/blog/liftoff
So performance is not really the key here to be honest.

For me improves the readability, because at a glance I understand that this value will not change for its scope, if I see a leet I expect it to change. In the example you're showing, the o reference will not change, so thanks to const I understand automatically that every o.something modification will be always over the same instance of o.

And well, is not the same situation as tabs vs spaces, because there are a bigger consensus over the javascript community. In fact, is the first time I meet someone prefering let over const in javascript, and I'm not able to find any article of debate or discussion on this topic. If you can point me some, I will read them, perhaps they change my mind. But right now, I don't see any advantage of let over const, and a lot of const over let.

**Comment by poveden** [comment]
These 2 guys state my feelings better that I could possibly do:

- [Let It Be - How to declare JavaScript variables](https://madhatted.com/2016/1/25/let-it-be)
- [Constantly Confusing ‘const’](http://web.archive.org/web/20160315114714/http://blog.getify.com/constantly-confusing-const/)

There's also some bickering here: [ES2015 `const` is not about immutability](https://mathiasbynens.be/notes/es6-const)

The "tabs and spaces" think is probably just in my head, for sure, as I don't have the "pulse" of the JavaScript community, but it seems to me that I'm not really alone here.

What kills me the most is things like this:

```js
for (const v of [1, 2, 3]) {
  console.log(v);
}
```

A `const` for a `for` loop? A constant that have a different value each time? Really? Yes, you will say "`v` is just being rebound on each iteration" (which is what's happening in the code, which I understand perfectly), but the _intent_ is not clear. A `const` is something that I _intend_ not to change (like magic numbers, or the BOM sequence). Variables used in some code block do not have that intent, even if they will never be reassigned.

If this is going to become a "thing", then I'm willing to follow @nulltoken's proposal to "let robots waste time so human beings can focus their review on other things". I'm not really comfortable with changing this, but I don't want also to drown in some pointless crusade and drag everybody else with me.

Maybe adding a comment somewhere clarifying why [`prefer-const`](https://eslint.org/docs/rules/prefer-const) is `off` on purpose?

**Comment by franher** [comment]
Hello, really happy to see AXA movement into Open Source is more and more a reality.

Having said that, I'd like to join your discussion :)

@poveden I get your point, the semantic of `const` could lead to the thought of it is something that won't change ever.

But we are JS developers, and we have to accept what `const` means in javascript since ES6 ([it became a standard since 2015](http://www.ecma-international.org/news/Publication%20of%20ECMA-262%206th%20edition.htm)). 

And of course, the benefits of using it. Some literature that could shed light on:

* https://medium.com/dailyjs/use-const-and-make-your-javascript-code-better-aac4f3786ca1
* https://ponyfoo.com/articles/var-let-const

Also, we should take a look at what the javascript community and the open source javascript industry is doing. The most opinionated set of rules for `ESLint`, [eslint-config-airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) has enabled by default the rule `prefer-const`.

Anyway, I think the discussion is really healthy and interesting.

I bet not only for enabling `prefer-const` rule but for using the whole [eslint-config-airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) configuration, or at least to try to decide a common rules for all the AXA projects.

**Comment by nulltoken** [comment]
@poveden I've no debate over `let` vs `const`. I tend to agree this is mostly noise. You're the maintainer. You decide ;-) And would you choose to close this issue, I'd be happy with your decision.

On a separate note, if linters are good enough to properly identify when a `let` should be a `const`, then compilers/optimizers should also be able to dynamically apply this transformation through an early pass (without forcing developers to care about that).

>Maybe adding a comment somewhere clarifying why prefer-const is off on purpose?

:+1: (BTW neat blog post you shared, I especially liked the part about the "constantly const followers")

**Comment by poveden** [comment]
Sorry for the long delay...

After pondering about all of your comments, and dedicating some time to understand Airbnb's rules, I've decided to stop being so stubborn and apply them.

Thank you all for your feedback!
